app:
  title: My Company Developer Portal
  baseUrl: https://elitecorpusa.com/backstage

organization:
  name: My Company

backend:
  baseUrl: https://elitecorpusa.com/backstage

  listen:
    port: 7007

  auth:
    keys:
      - secret: ${BACKEND_SECRET}

  cors:
    origin:
      - https://elitecorpusa.com/backstage
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true

  database:
    client: pg
    connection:
      host: /cloudsql/${PROJECT_ID}:${REGION}:backstage-db
      user: backstage
      password: ${BACKSTAGE_DB_PASS}
      database: backstage

  reading:
    allow:
      - host: github.com
      - host: raw.githubusercontent.com

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

auth:
  environment: production

  providers:
    okta:
      development:
        clientId: ${AUTH_OKTA_CLIENT_ID}
        clientSecret: ${AUTH_OKTA_CLIENT_SECRET}
        audience: ${AUTH_OKTA_DOMAIN}
    google:
      production:
        clientId: ${AUTH_GOOGLE_CLIENT_ID}
        clientSecret: ${AUTH_GOOGLE_CLIENT_SECRET}

techdocs:
  builder: external

  generator:
    runIn: docker

  publisher:
    type: googleGcs

    googleGcs:
      bucketName: ${PROJECT_ID}-techdocs

scaffolder:
  defaultAuthor:
    name: Backstage
    email: backstage@elitecorpusa.com

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration

  rules:
    - allow:
        - Component
        - System
        - API
        - Resource
        - Location
        - Group
        - User
        - Template

permission:
  enabled: true